=== Crease29/core/System/SystemConfig/Schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="card" type="card" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="card">
        <xs:sequence>
            <xs:element name="title" type="translatableString" maxOccurs="unbounded"/>
            <xs:element name="input-field" type="input-field" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="input-field">
        <xs:sequence>
            <xs:element name="name" type="name"/>
            <xs:element name="label" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="placeholder" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="helpText" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="copyable" type="xs:boolean" minOccurs="0"/>
            <xs:element name="disabled" type="xs:boolean" minOccurs="0"/>
            <xs:element name="options" type="option-collection" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="type" default="text"/>
    </xs:complexType>
    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="textarea"/>
            <xs:enumeration value="combo"/>
            <xs:enumeration value="select"/>
            <xs:enumeration value="radio"/>
            <xs:enumeration value="checkbox"/>
            <xs:enumeration value="switch"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="password"/>
            <xs:enumeration value="inline"/>
            <xs:enumeration value="date"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="translatableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="languageCode" default="en_GB"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="languageCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2}_[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="option-collection">
        <xs:sequence>
            <xs:element name="option" type="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="label" type="translatableString" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]{4,}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Crease29/core/System/Resources/config/listing.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">
    <card>
        <title>Listing</title>
        <title lang="de-DE">Produktliste</title>

        <input-field type="bool">
            <name>allowBuyInListing</name>
            <label>show buy button in listing</label>
            <label lang="de-DE">Kaufenbutton im Produktlisting anzeigen</label>
        </input-field>
    </card>
</config>

=== Crease29/core/Framework/Test/Plugin/_fixtures/valid_config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../Plugin/Schema/config.xsd">
    <card>
        <title>Basic configuration</title>
        <title lang="de_DE">Grundeinstellungen</title>
        <sw-field>
            <name>email</name>
            <label>eMail</label>
            <label lang="de_DE">E-Mail</label>
            <placeholder>Enter your eMail address</placeholder>
            <placeholder lang="de_DE">Bitte gib deine E-Mail Adresse ein</placeholder>
            <copyable>true</copyable>
        </sw-field>

        <sw-field type="select">
            <name>mailMethod</name>
            <label>Mailing protocol</label>
            <label lang="de_DE">E-Mail Versand Protokoll</label>
            <placeholder>Choose your preferred transfer method</placeholder>
            <placeholder lang="de_DE">Bitte w√§hle dein bevorzugtes Versand Protokoll</placeholder>
            <options>
                <option>
                    <value>smtp</value>
                    <label>SMTP</label>
                </option>
                <option>
                    <value>pop3</value>
                    <label>POP3</label>
                </option>
            </options>
        </sw-field>
    </card>
</config>

=== Crease29/core/System/Resources/config/privacy.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">
    <card>
        <title>Privacy</title>
        <title lang="de-DE">Datenschutz</title>

        <input-field type="bool">
            <name>doiNewsletter</name>
            <label>Newsletter Double-Opt-in</label>
            <helpText>Enables Double-Opt-in for newsletters</helpText>
            <helpText lang="de-DE">Aktiviert Double-Opt-in f√ºr Newsletter</helpText>
        </input-field>
    </card>
</config>
